stages:
  - lint
  - test
  - build
  - deploy

variables:
  DOCKERHUB_USERNAME: "<your_dockerhub_username>"
  DOCKERHUB_PASSWORD: "<your_dockerhub_password>"
  BACKEND_IMAGE: "<your_dockerhub_username>/backend-image"
  FRONTEND_IMAGE: "<your_dockerhub_username>/frontend-image"
  NGINX_IMAGE: "<your_dockerhub_username>/nginx-image"

lint:
  stage: lint
  image: php:8.1
  script:
    - apt-get update -yqq
    - apt-get install -yqq git unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - cd backend
    - composer install --prefer-dist --no-scripts --no-interaction --optimize-autoloader
    - ./vendor/bin/php-cs-fixer fix . --show-progress=dots --dry-run --diff --verbose --ansi
  only:
    - merge_requests
    - main
    - dev

test:backend:
  stage: test
  image: php:8.1-cli
  before_script:
    - docker-php-ext-install pdo pdo_mysql
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - cd backend
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  script:
    - vendor/bin/phpunit --coverage-text --colors=never
  only:
    - branches
